# Cloud Build configuration for PeoplePerson
# Builds Docker images only - deployment handled by Terraform

substitutions:
  _PROJECT_ID: peopleperson-app

options:
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON
  machineType: 'E2_HIGHCPU_8'

steps:
  # Build Docker images

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/peopleperson-api:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'api'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/peopleperson-frontend:latest'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=AIzaSyAgmbRX4MZROeWd1YuxxPy6WQr7kndBkRU'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=peopleperson-app.firebaseapp.com'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=peopleperson-app'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=peopleperson-app.firebasestorage.app'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=1076925812481'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=1:1076925812481:web:a00140472692ffc69bd500'
      - '--build-arg'
      - 'VITE_FIREBASE_MEASUREMENT_ID=G-0B9YP38G11'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'webclient'

  # Push all images

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args: ['push', '--all-tags', 'gcr.io/${_PROJECT_ID}/peopleperson-api']
    waitFor: ['build-api']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args: ['push', '--all-tags', 'gcr.io/${_PROJECT_ID}/peopleperson-frontend']
    waitFor: ['build-frontend']


images:
  - 'gcr.io/${_PROJECT_ID}/peopleperson-api:latest'
  - 'gcr.io/${_PROJECT_ID}/peopleperson-frontend:latest'

timeout: '1800s'