# Cloud Build configuration for PeoplePerson
# Handles both staging and production deployments based on branch

substitutions:
  _PROJECT_ID: peopleperson-app
  _ENVIRONMENT: staging  # Default to staging, override in triggers

options:
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON
  machineType: 'E2_HIGHCPU_8'

steps:
  # Build Docker images

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/peopleperson-api:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/peopleperson-api:${BRANCH_NAME}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/peopleperson-api:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'api'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/peopleperson-frontend:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/peopleperson-frontend:${BRANCH_NAME}'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/peopleperson-frontend:latest'
      - '--build-arg'
      - 'VITE_APP_ENVIRONMENT=${_ENVIRONMENT}'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=AIzaSyAgmbRX4MZROeWd1YuxxPy6WQr7kndBkRU'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=peopleperson-app.firebaseapp.com'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=peopleperson-app'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=peopleperson-app.firebasestorage.app'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=1076925812481'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=1:1076925812481:web:a00140472692ffc69bd500'
      - '--build-arg'
      - 'VITE_FIREBASE_MEASUREMENT_ID=G-0B9YP38G11'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'webclient'

  # Push all images

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args: ['push', '--all-tags', 'gcr.io/${_PROJECT_ID}/peopleperson-api']
    waitFor: ['build-api']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args: ['push', '--all-tags', 'gcr.io/${_PROJECT_ID}/peopleperson-frontend']
    waitFor: ['build-frontend']

  # Deploy new images to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'peopleperson-api-${_ENVIRONMENT}'
      - '--image=gcr.io/${_PROJECT_ID}/peopleperson-api:${BRANCH_NAME}'
      - '--region=us-central1'
      - '--project=${_PROJECT_ID}'
    waitFor: ['push-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'peopleperson-frontend-${_ENVIRONMENT}'
      - '--image=gcr.io/${_PROJECT_ID}/peopleperson-frontend:${BRANCH_NAME}'
      - '--region=us-central1'
      - '--project=${_PROJECT_ID}'
    waitFor: ['push-frontend']

images:
  - 'gcr.io/${_PROJECT_ID}/peopleperson-api:${SHORT_SHA}'
  - 'gcr.io/${_PROJECT_ID}/peopleperson-api:${BRANCH_NAME}'
  - 'gcr.io/${_PROJECT_ID}/peopleperson-frontend:${SHORT_SHA}'
  - 'gcr.io/${_PROJECT_ID}/peopleperson-frontend:${BRANCH_NAME}'

timeout: '1800s'